Doesn't give the same results as in the paper, why?

In [1]:
import sys
sys.path.append('../')
from os import path

from climatenet.utils.data import ClimateDatasetLabeled, ClimateDataset
from climatenet.models import CGNet
from climatenet.utils.utils import Config
from climatenet.track_events import track_events
from climatenet.analyze_events import analyze_events
from climatenet.visualize_events import visualize_events

with the baseline model from 2020

In [2]:
config = Config('../models/original_baseline_model/config.json')
cgnet = CGNet(model_path='../models/original_baseline_model')
test = ClimateDatasetLabeled('../data/test', config)
cgnet.evaluate(test)

100%|██████████| 8/8 [00:36<00:00,  4.51s/it]

Evaluation stats:
[[4.8066605e+07 2.5531500e+05 2.3323820e+06]
 [1.0442700e+05 1.9162400e+05 5.4300000e+02]
 [8.9359000e+05 2.1151000e+04 2.1032590e+06]]
IOUs:  [0.93057981 0.33438732 0.39306456] , mean:  0.552677231299996


with the baseline model from 2022

In [3]:
config = Config('../models/new_baseline_model/config.json')
cgnet = CGNet(model_path='../models/new_baseline_model')
test = ClimateDatasetLabeled('../data/test', config)
cgnet.evaluate(test)

RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /tmp/pip-req-build-8yht7tdu/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /tmp/pip-req-build-8yht7tdu/caffe2/serialize/inline_container.cc:132)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6d (0x7f21e0aea2ad in /anaconda/envs/climatenet/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: caffe2::serialize::PyTorchStreamReader::init() + 0x25db (0x7f21b2bb7a1b in /anaconda/envs/climatenet/lib/python3.8/site-packages/torch/lib/libtorch.so)
frame #2: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x7b (0x7f21b2bb8f2b in /anaconda/envs/climatenet/lib/python3.8/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x6969ce (0x7f21d344f9ce in /anaconda/envs/climatenet/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x158a39 (0x7f21d2f11a39 in /anaconda/envs/climatenet/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #5: PyCFunction_Call + 0x56 (0x558d51d4cf76 in /anaconda/envs/climatenet/bin/python)
frame #6: _PyObject_MakeTpCall + 0x22f (0x558d51d0a85f in /anaconda/envs/climatenet/bin/python)
frame #7: <unknown function> + 0x18bfdc (0x558d51d58fdc in /anaconda/envs/climatenet/bin/python)
frame #8: PyVectorcall_Call + 0x71 (0x558d51d0a041 in /anaconda/envs/climatenet/bin/python)
frame #9: <unknown function> + 0x18c92a (0x558d51d5992a in /anaconda/envs/climatenet/bin/python)
frame #10: _PyObject_MakeTpCall + 0x1a4 (0x558d51d0a7d4 in /anaconda/envs/climatenet/bin/python)
frame #11: _PyEval_EvalFrameDefault + 0x4596 (0x558d51d91f56 in /anaconda/envs/climatenet/bin/python)
frame #12: _PyEval_EvalCodeWithName + 0x659 (0x558d51d57e19 in /anaconda/envs/climatenet/bin/python)
frame #13: _PyObject_FastCallDict + 0x20c (0x558d51d5948c in /anaconda/envs/climatenet/bin/python)
frame #14: _PyObject_Call_Prepend + 0x63 (0x558d51d59733 in /anaconda/envs/climatenet/bin/python)
frame #15: <unknown function> + 0x18c8ca (0x558d51d598ca in /anaconda/envs/climatenet/bin/python)
frame #16: _PyObject_MakeTpCall + 0x1a4 (0x558d51d0a7d4 in /anaconda/envs/climatenet/bin/python)
frame #17: _PyEval_EvalFrameDefault + 0x475 (0x558d51d8de35 in /anaconda/envs/climatenet/bin/python)
frame #18: _PyEval_EvalCodeWithName + 0x2d2 (0x558d51d57a92 in /anaconda/envs/climatenet/bin/python)
frame #19: _PyFunction_Vectorcall + 0x1e3 (0x558d51d58943 in /anaconda/envs/climatenet/bin/python)
frame #20: <unknown function> + 0x10077f (0x558d51ccd77f in /anaconda/envs/climatenet/bin/python)
frame #21: _PyEval_EvalCodeWithName + 0x2d2 (0x558d51d57a92 in /anaconda/envs/climatenet/bin/python)
frame #22: _PyFunction_Vectorcall + 0x1e3 (0x558d51d58943 in /anaconda/envs/climatenet/bin/python)
frame #23: _PyObject_FastCallDict + 0x24b (0x558d51d594cb in /anaconda/envs/climatenet/bin/python)
frame #24: _PyObject_Call_Prepend + 0x63 (0x558d51d59733 in /anaconda/envs/climatenet/bin/python)
frame #25: <unknown function> + 0x18c8ca (0x558d51d598ca in /anaconda/envs/climatenet/bin/python)
frame #26: _PyObject_MakeTpCall + 0x1a4 (0x558d51d0a7d4 in /anaconda/envs/climatenet/bin/python)
frame #27: _PyEval_EvalFrameDefault + 0x11d0 (0x558d51d8eb90 in /anaconda/envs/climatenet/bin/python)
frame #28: _PyEval_EvalCodeWithName + 0x2d2 (0x558d51d57a92 in /anaconda/envs/climatenet/bin/python)
frame #29: PyEval_EvalCodeEx + 0x44 (0x558d51d58754 in /anaconda/envs/climatenet/bin/python)
frame #30: PyEval_EvalCode + 0x1c (0x558d51de6edc in /anaconda/envs/climatenet/bin/python)
frame #31: <unknown function> + 0x24f083 (0x558d51e1c083 in /anaconda/envs/climatenet/bin/python)
frame #32: <unknown function> + 0x140699 (0x558d51d0d699 in /anaconda/envs/climatenet/bin/python)
frame #33: <unknown function> + 0xfeb84 (0x558d51ccbb84 in /anaconda/envs/climatenet/bin/python)
frame #34: _PyGen_Send + 0x149 (0x558d51d51dc9 in /anaconda/envs/climatenet/bin/python)
frame #35: _PyEval_EvalFrameDefault + 0x49a3 (0x558d51d92363 in /anaconda/envs/climatenet/bin/python)
frame #36: _PyGen_Send + 0x149 (0x558d51d51dc9 in /anaconda/envs/climatenet/bin/python)
frame #37: _PyEval_EvalFrameDefault + 0x49a3 (0x558d51d92363 in /anaconda/envs/climatenet/bin/python)
frame #38: _PyGen_Send + 0x149 (0x558d51d51dc9 in /anaconda/envs/climatenet/bin/python)
frame #39: <unknown function> + 0x1701cd (0x558d51d3d1cd in /anaconda/envs/climatenet/bin/python)
frame #40: <unknown function> + 0x10075e (0x558d51ccd75e in /anaconda/envs/climatenet/bin/python)
frame #41: _PyFunction_Vectorcall + 0x10b (0x558d51d5886b in /anaconda/envs/climatenet/bin/python)
frame #42: <unknown function> + 0xfeb84 (0x558d51ccbb84 in /anaconda/envs/climatenet/bin/python)
frame #43: _PyFunction_Vectorcall + 0x10b (0x558d51d5886b in /anaconda/envs/climatenet/bin/python)
frame #44: <unknown function> + 0x10075e (0x558d51ccd75e in /anaconda/envs/climatenet/bin/python)
frame #45: _PyEval_EvalCodeWithName + 0x2d2 (0x558d51d57a92 in /anaconda/envs/climatenet/bin/python)
frame #46: _PyFunction_Vectorcall + 0x1e3 (0x558d51d58943 in /anaconda/envs/climatenet/bin/python)
frame #47: <unknown function> + 0x18be79 (0x558d51d58e79 in /anaconda/envs/climatenet/bin/python)
frame #48: PyVectorcall_Call + 0x71 (0x558d51d0a041 in /anaconda/envs/climatenet/bin/python)
frame #49: _PyEval_EvalFrameDefault + 0x1fdb (0x558d51d8f99b in /anaconda/envs/climatenet/bin/python)
frame #50: _PyEval_EvalCodeWithName + 0x659 (0x558d51d57e19 in /anaconda/envs/climatenet/bin/python)
frame #51: <unknown function> + 0x18bd20 (0x558d51d58d20 in /anaconda/envs/climatenet/bin/python)
frame #52: <unknown function> + 0x10011a (0x558d51ccd11a in /anaconda/envs/climatenet/bin/python)
frame #53: _PyGen_Send + 0x149 (0x558d51d51dc9 in /anaconda/envs/climatenet/bin/python)
frame #54: _PyEval_EvalFrameDefault + 0x49a3 (0x558d51d92363 in /anaconda/envs/climatenet/bin/python)
frame #55: _PyGen_Send + 0x149 (0x558d51d51dc9 in /anaconda/envs/climatenet/bin/python)
frame #56: _PyEval_EvalFrameDefault + 0x49a3 (0x558d51d92363 in /anaconda/envs/climatenet/bin/python)
frame #57: _PyGen_Send + 0x149 (0x558d51d51dc9 in /anaconda/envs/climatenet/bin/python)
frame #58: _PyEval_EvalFrameDefault + 0x49a3 (0x558d51d92363 in /anaconda/envs/climatenet/bin/python)
frame #59: _PyGen_Send + 0x149 (0x558d51d51dc9 in /anaconda/envs/climatenet/bin/python)
frame #60: _PyEval_EvalFrameDefault + 0x49a3 (0x558d51d92363 in /anaconda/envs/climatenet/bin/python)
frame #61: _PyGen_Send + 0x149 (0x558d51d51dc9 in /anaconda/envs/climatenet/bin/python)
frame #62: <unknown function> + 0x6edd (0x7f220d02fedd in /anaconda/envs/climatenet/lib/python3.8/lib-dynload/_asyncio.cpython-38-x86_64-linux-gnu.so)
frame #63: <unknown function> + 0x7718 (0x7f220d030718 in /anaconda/envs/climatenet/lib/python3.8/lib-dynload/_asyncio.cpython-38-x86_64-linux-gnu.so)
